theme = "semi-native"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
dynamic_width = true
player = "spotify"
on_collapsed_click = "spotify"
buttons = ["prev","play", "next"]

[[block]]
block = "github"
format = "{total}|{author}|{comment}|{mention}|{review_requested}"
hide_if_total_is_zero = true

[[block]]
block = "uptime"
interval = 1

[[block]]
block = "custom"
command = "uname -r"
interval = "once"

[[block]]
block = "battery"
device = "BAT1"
interval = 30
format = "{percentage}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlo1"
format = "{speed_down} {speed_up}"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%A %B %e %T %Y"

[[block]]
block = "custom"
interval = 999999
command = "echo '\uF011'"
on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"
